version: "3.1"

services:
  kms:
    image: kurento/kurento-media-server:7.0.1
    container_name: kms
    restart: on-failure
    ports:
      - "8888:8888"
      - "40000-40100:40000-40100/udp"
    environment:
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=40100
      - GST_DEBUG=2,Kurento*:4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/kurento"]
      interval: 30s
      timeout: 10s
      retries: 5

  openvidu-server:
    image: openvidu/openvidu-server:2.28.0
    container_name: openvidu-server
    restart: on-failure
    depends_on:
      - kms
    ports:
      - "4443:4443"
    volumes:
      - ./config:/config
      - ./recordings:/opt/openvidu/recordings
      - ./logs:/opt/openvidu/logs
      - ./.env:/opt/openvidu/.env
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OPENVIDU_RECORDING=${OPENVIDU_RECORDING:-false}
      - OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings
      - OPENVIDU_RECORDING_PUBLIC_ACCESS=false
      - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP:-localhost}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
      - CERTIFICATE_TYPE=${CERTIFICATE_TYPE:-selfsigned}
      - HTTPS_PORT=${HTTPS_PORT:-4443}
      - KMS_URIS=["ws://kms:8888/kurento"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/openvidu/api"]
      interval: 30s
      timeout: 10s
      retries: 5

  permission-server:
    build:
      context: ./permission-server
      dockerfile: Dockerfile
    container_name: permission-server
    restart: on-failure
    environment:
      - OPENVIDU_SECRET=MY_SECRET
    ports:
      - "5001:5000"
    depends_on:
      - openvidu-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  coturn:
    image: openvidu/openvidu-coturn:2.29.0
    container_name: openvidu-coturn
    restart: on-failure
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    env_file:
      - .env
    volumes:
      - ./coturn:/opt/openvidu/coturn
    healthcheck:
      test: ["CMD", "turnserver", "-h"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: openvidu/openvidu-proxy:2.29.0
    container_name: openvidu-proxy
    restart: on-failure
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PROXY_MODE=CE
      - CERTIFICATE_TYPE=selfsigned
      - DOMAIN_OR_PUBLIC_IP=localhost
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: openvidu-app
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - OPENVIDU_URL=https://openvidu-server:4443
      - OPENVIDU_SECRET=${OPENVIDU_SECRET:-MY_SECRET}
    depends_on:
      - openvidu-server
